services:
  web:
#    image: nginx:stable-bookworm
#    image: ark-mods-web:safe
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #  - ./templates:/etc/nginx/templates
    #  - ./build:/usr/share/nginx/html
#    ports:
#     - "8080:80"
    env_file:
      - path: ./.env
        required: true
#    environment:
#     - NGINX_HOST=ark-mods.nebre.net
#     - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - default
      - proxy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.arkmods-http.rule=Host(`ark-mods.nebre.net`,`ark-mods-origin.nebre.net`)"
      - "traefik.http.routers.arkmods-http.entrypoints=web"
      - "traefik.http.routers.arkmods-http.middlewares=arkmods-https"
      - "traefik.http.routers.arkmods.rule=Host(`ark-mods.nebre.net`,`ark-mods-origin.nebre.net`)"
      - "traefik.http.routers.arkmods.entrypoints=websecure"
      - "traefik.http.routers.arkmods.tls.certresolver=myresolver"
      - "traefik.http.routers.arkmods.tls=true"
      - "traefik.http.middlewares.arkmods-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.arkmods-https.redirectscheme.permanent=true"

networks:
    proxy:
      external: true

